db.url=jdbc:mysql://mysql-24ec3754-prject.b.aivencloud.com:23268/defaultdb?useSSL=true&trustServerCertificate=true
db.user=avnadmin
db.password=AVNS_MUnq7F2SF5Li4obd6GP

server.post=8080

# file này để ko bị lỗi password
# nhớ thay tên file thành application.properties
# password nếu cần nhắn t(lân) gửi cho
# :3
