db.url=jdbc:mysql://mysql-24ec3754-prject.b.aivencloud.com:23268/defaultdb?useSSL=true&trustServerCertificate=true
db.user=avnadmin
db.password=INSERT_PASSWORD_HERE

# file này ?? ko b? l? password
# nh? thay tên file thành application.properties
# password n?u c?n nh?n t(lân) g?i cho
# :3