db.url=jdbc:mysql://mysql-24ec3754-prject.b.aivencloud.com:23268/defaultdb?useSSL=true&trustServerCertificate=true&connectTimeout=30000&socketTimeout=60000
db.user=avnadmin
db.password=AVNS_5zRsqM5L8lWsvYIKcf5

server.post=8080
